services:
  vibegateway:
    image: dspworks/vibegateway:1.0.1
    container_name: vibegateway
    restart: unless-stopped
    devices:
      - "/dev/ttyS6:/dev/ttyS6"
    volumes:
      - ${APP_DATA_DIR}/data/database.php:/var/www/html/vibegateway/web/application/config/database.php
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=dspworks
      - DB_NAME=vshgateway
    depends_on:
      vibegateway-mariadb:
        condition: service_healthy
    x-runtipi:
      is_main: true
      internal_port: 80
  vibegateway-mariadb:
    image: mariadb:11.4
    container_name: vibegateway-mariadb
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/mariadb_data:/var/lib/mysql
      - ${APP_DATA_DIR}/data/vshgateway.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=dspworks
      - MYSQL_DATABASE=vshgateway
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
x-runtipi:
  schema_version: 2