services:
  vibegateway:
    image: dspworks/vibegateway:1.0.1
    container_name: vibegateway
    restart: unless-stopped
    devices:
      - "/dev/ttyS6:/dev/ttyS6"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=dspworks
      - DB_NAME=vshgateway
    depends_on:
      mariadb:
        condition: service_healthy
    x-runtipi:
      is_main: true
      internal_port: 80
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/mariadb_data:/var/lib/mysql
      - ${APP_DATA_DIR}/data/vshgateway.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=dspworks
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=vshgateway
    healthcheck:
      test:
        - CMD
        - mariadb-admin
        - ping
        - -u
        - root
        - -p
        - dspworks
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
x-runtipi:
  schema_version: 2